MHProductsBundle_admin_products:
    resource: "@MHProductsBundle/Resources/config/routing/product.yml"
    prefix:   /products

MHProductsBundle_admin_product-detail-values:
    resource: "@MHProductsBundle/Resources/config/routing/detailvalue.yml"
    prefix:   /product-detail-values

MHProductsBundle_admin_primary-categories:
    resource: "@MHProductsBundle/Resources/config/routing/primarycategory.yml"
    prefix:   /primary-categories

MHProductsBundle_admin_sub-categories:
    resource: "@MHProductsBundle/Resources/config/routing/subcategory.yml"
    prefix:   /sub-categories

MHProductsBundle_admin_uploads:
    resource: "@MHProductsBundle/Resources/config/routing/upload.yml"
    prefix:   /uploads

MHStoreBundle_admin_settings:
    resource: "@MHStoreBundle/Resources/config/routing/settings.yml"
    prefix:   /settings

MHProductsBundle_admin_orders:
    resource: "@MHProductsBundle/Resources/config/routing/customerorder.yml"
    prefix:   /orders
