MH\ProductsBundle\Entity\Upload:
    properties:
        file:
            - File:
                maxSize: 6000000

MH\ProductsBundle\Entity\PrimaryCategory:
    properties:
        file:
            - File:
                maxSize: 6000000

MH\ProductsBundle\Entity\SubCategory:
    properties:
        file:
            - File:
                maxSize: 6000000