admin_sub-categories:
    pattern:  /
    defaults: { _controller: "MHProductsBundle:SubCategory:index" }

admin_sub-categories_show:
    pattern:  /{id}/show
    defaults: { _controller: "MHProductsBundle:SubCategory:show" }

admin_sub-categories_new:
    pattern:  /new
    defaults: { _controller: "MHProductsBundle:SubCategory:new" }

admin_sub-categories_create:
    pattern:  /create
    defaults: { _controller: "MHProductsBundle:SubCategory:create" }
    requirements: { _method: post }

admin_sub-categories_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MHProductsBundle:SubCategory:edit" }

admin_sub-categories_update:
    pattern:  /{id}/update
    defaults: { _controller: "MHProductsBundle:SubCategory:update" }
    requirements: { _method: post|put }

admin_sub-categories_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MHProductsBundle:SubCategory:delete" }
    requirements: { _method: post|delete }
