admin_uploads:
    pattern:  /
    defaults: { _controller: "MHProductsBundle:Upload:index" }

admin_uploads_show:
    pattern:  /{id}/show
    defaults: { _controller: "MHProductsBundle:Upload:show" }

admin_uploads_new:
    pattern:  /new
    defaults: { _controller: "MHProductsBundle:Upload:new" }

admin_uploads_create:
    pattern:  /create
    defaults: { _controller: "MHProductsBundle:Upload:create" }
    requirements: { _method: post }

admin_uploads_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MHProductsBundle:Upload:edit" }

admin_uploads_update:
    pattern:  /{id}/update
    defaults: { _controller: "MHProductsBundle:Upload:update" }
    requirements: { _method: post|put }

admin_uploads_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MHProductsBundle:Upload:delete" }
    requirements: { _method: post|delete }
