mh_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MHUserBundle:Default:index }

MHUserBundle_customers:
    resource: "@MHUserBundle/Resources/config/routing/customer.yml"
    prefix:   /account
